edition = "2023";

package igpb.v1;

import "buf/validate/validate.proto";
import "google/api/field_behavior.proto";

// CopyrightCheckStatus represents the copyright detection status for uploaded videos
message CopyrightCheckStatus {
  // Whether matches were found indicating copyright infringement
  bool matches_found = 1;
  // The status of the copyright detection process
  string status = 2 [(buf.validate.field).string = {
    min_len: 1
    pattern: "^(completed|error|in_progress|not_started)$"
  }];
}

// InstagramFieldContainerResponse represents an Instagram container for media publication
message InstagramFieldContainerResponse {
  // The copyright check status for the container (if applicable)
  CopyrightCheckStatus copyright_check_status = 1;
  // The identifier of the Instagram container
  string id = 2 [
    (buf.validate.field).string = {min_len: 1},
    (google.api.field_behavior) = REQUIRED
  ];
  // Publication status. If status_code is ERROR, this value will be an error subcode
  string status = 3 [(buf.validate.field).string = {min_len: 1}];
  // The publication status code of the container.
  // Possible values: EXPIRED, ERROR, FINISHED, IN_PROGRESS, PUBLISHED
  string status_code = 4 [
    (buf.validate.field).string = {
      in: [
        "EXPIRED",
        "ERROR",
        "FINISHED",
        "IN_PROGRESS",
        "PUBLISHED"
      ]
    },
    (google.api.field_behavior) = REQUIRED
  ];
}
