edition = "2023";

package igpb.v1;

import "google/api/field_behavior.proto";
import "google/protobuf/timestamp.proto";

message InstagramMetricInsightResponse {
  repeated MetricInsight data = 1;
  // The payload of the webhook, which can contain additional information about the message, such as attachments or other metadata. This field is flexible and can be used to include any relevant data that may not fit into the predefined fields above.
  bytes payload = 2;
}

message MetricInsight {
  string description = 1;
  string id = 2 [(google.api.field_behavior) = REQUIRED];
  string name = 3;
  string period = 4;
  string title = 5;
  repeated MetricValue values = 6;
}

message MetricValue {
  google.protobuf.Timestamp end_time = 1;
  int64 value = 2;
}
