edition = "2023";

package generalpb.v1;

import "google/api/field_behavior.proto";

// SuccessResponse represents a generic success response
message SuccessResponse {
  // The payload of the webhook, which can contain additional information about the message, such as attachments or other metadata. This field is flexible and can be used to include any relevant data that may not fit into the predefined fields above.
  bytes payload = 1;
  // Whether the operation was successful
  bool success = 2 [(google.api.field_behavior) = REQUIRED];
}
