package message

type Button struct {
	Id    string `json:"id"`    //  Don't have space begin or end ofof id of button, max 256 characters
	Type  string `json:"type"`  // Only type "reply"(in buttons response)
	Title string `json:"title"` // Don't empty string and max 20 characters. Must be unique within the message. Emoji support is offered, but not Markdown. Maximum length: 20 characters.
}

type Row struct {
	Id          string `json:"id" validate:"required"`    // Required, .Longitude <= 24 characters
	Title       string `json:"title" validate:"required"` // Required, .Longitude <= 200 characters
	Description string `json:"description,omitempty"`     // Optional, .Longitude <= 72 characters
}

type Product struct {
	/*
		Required in message of type multiple products
		Id(unique) of the product in a catalog. For obtain the id see the Manager of Sales of Meta:
		https://developers.facebook.com/micro_site/url/?click_from_context_menu=true&country=BR&destination=https%3A%2F%2Fbusiness.facebook.com%2Fcommerce%2F&event_type=click&last_nav_impression_id=01G2Htn0xU0Wb5E3e&max_percent_page_viewed=47&max_viewport_height_px=874&max_viewport_width_px=1920&orig_http_referrer=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fwhatsapp%2Fcloud-api%2Freference%2Fmessages&orig_request_uri=https%3A%2F%2Fdevelopers.facebook.com%2Fajax%2Fdocs%2Fnav%2F%3Fpath1%3Dwhatsapp%26path2%3Dcloud-api%26path3%3Dreference%26path4%3Dmessages&region=latam&scrolled=true&session_id=3CqQfPWvI8mfs6WFQ&site=developers
		List Marketplace -> Select Meketplace -> Catalog -> Articles -> Product(Article) needed id
	*/
	ProductRetailerID string `json:"product_retailer_id"`
}

type Section struct {
	Title        string    `json:"title" validate:"required"` // Required, .Longitude <= 24 characters
	ProductItems []Product `json:"product_items"`             // Required in message of type multiple products
	Rows         []Row     `json:"rows"`                      // required in message of list. Contains a list of rows, max 10
}

type FlowActionPayload struct {
	Screen string   `json:"screen"` // Optional. Id of the first screen of the process. Default: "FIRST_ENTRY_SCREEN"
	Data   struct{} `json:"data"`   // Optional. Data in of First entry screen. Must object not empty
}

type ParametersAction struct {
	DisplayText string `json:"display_text"`
	URL         string `json:"url"`
}

type Action struct {
	Content string   `json:"button"`  // Content of Button. Required in message of list, can't be empty string, longitude <= 20 characters
	Buttons []Button `json:"buttons"` // Required in message of buttons response. It can to 3 buttons.
	/*
		Required in message of product individual and multiple.
		Id(unique) of the catalog of facebook linked to the whatsapp business account.
		This id can recover the from the Manager of Sales of Meta.
	*/
	CatalogID string `json:"catalog_id"`
	/* Id(unique) of the product in a catalog. For obtain the id see the Manager of Sales of Meta:
	https://developers.facebook.com/micro_site/url/?click_from_context_menu=true&country=BR&destination=https%3A%2F%2Fbusiness.facebook.com%2Fcommerce%2F&event_type=click&last_nav_impression_id=01G2Htn0xU0Wb5E3e&max_percent_page_viewed=47&max_viewport_height_px=874&max_viewport_width_px=1920&orig_http_referrer=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fwhatsapp%2Fcloud-api%2Freference%2Fmessages&orig_request_uri=https%3A%2F%2Fdevelopers.facebook.com%2Fajax%2Fdocs%2Fnav%2F%3Fpath1%3Dwhatsapp%26path2%3Dcloud-api%26path3%3Dreference%26path4%3Dmessages&region=latam&scrolled=true&session_id=3CqQfPWvI8mfs6WFQ&site=developers
	List Marketplace -> Select Meketplace -> Catalog -> Articles -> Product(Article) needed id
	*/
	ProductRetailerID  string    `json:"product_retailer_id"`
	Sections           []Section `json:"sections"`             // Required in message of list and multiple products
	FlowMessageVersion string    `json:"flow_message_version"` // required in message of proccess. Must be 3
	FlowId             string    `json:"flow_id"`              // required in message of proccess at least that establish the "flow_name". Don't use with "flow_name"
	FlowName           string    `json:"flow_name"`            // required in message of proccess at least that establish the "flow_id". Don't use with "flow_id"
	FlowCta            string    `json:"flow_cta"`             // required in message of proccess. Text of button of call to action. ej: "Register" and max 20 characters. Emoji not support.
	Mode               string    `json:"mode"`                 // Optional in case message of proccess. The mode actual of process, whether it is "draft" or "publish". Default is "publish"
	FlowToken          string    `json:"flow_token"`           // Optional in case of message proccess. One token generated by Enterprise and used with identifier. Default value is "unused".
	/*
	 // Optional in case of message proccess. "navegate" or "data_exchange".
	 Use "navigate" by define the one display with part of the mensage.
	 Use "data_exchange" by define the cases advance in that you provide the point of conextion by first Display.
	 Default value is "navigate".
	*/
	FlowAction        string              `json:"flow_action"`
	FlowActionPayload FlowActionPayload   `json:"flow_action_payload"` // Optional in case of message proccess if only "flow_action" is "navigate".
	Name              string              `json:"name"`                // Optional. Only used in case of message interactive is "cta_url"
	ParametersAction  `json:"parameters"` // Optional. Only used in case of message interactive is "cta_url"
}

type BodyFooter struct {
	Text string `json:"text"` // Required if Object contens footer or body.  longitude <= 1024 characters if type is "body" else 64 characters for "footer".
}

type HeaderInteractive struct {
	/*
		Required. Types are
		"text": use with message of (list, buttons response, products multiple),
		"video": use for button response,
		"image": use for button response,
		"document": use for button response
	*/
	Type     string `json:"type" validate:"required"`
	Text     string `json:"text"`     // Required if type is "text". Text of header. Max 60 characters. Support Emoji and not Markdown .
	Document Media  `json:"document"` // Required if type is "document". Contains object Media of this document.
	Image    Media  `json:"image"`    // Required if type is "image". Contains object Media of this image.
	SubText  string `json:"sub_text"` // Optional. Text of header.Max 60 characters.	Support Emoji and not Markdown
	Video    Media  `json:"video"`    // Required if type is "video". Contains object Media of this video.
}

type InteractiveProto struct {
	Action            `json:"action" validate:"required"` // Required. Action after read the message
	Body              BodyFooter                          `json:"body"`   // Optional for type product, required for others. One Object with body of message
	Footer            BodyFooter                          `json:"footer"` // Optional. One Object with footer of message
	HeaderInteractive `json:"header"`                     // Required for "product_list". Optional for others. Don't configure if interactive is type "product" .
	/*
		Required. is
		 button: for buttons response,
		 list: for message of list,
		 product: for message of product individual,
		 catalog_message: for message of catalog message,
		 product_list: for message of multiple products,
		 flow: for message of proccess
		 cta_url: for message of Button URL
	*/
	Type string `json:"type" validate:"required"`
}
